### ISSUE TITLE
High CPU then out of memory parsing invalid Python

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [Tobias-Kohn/TigerPython-Parser#2]
Running

```javascript
TPyParser.findAllErrors("{1:1=")
```

uses 100% of a core and then crashes the Chrome tab.

This was stripped down from something slightly more meaningful, but still invalid Python!

Running the same in NodeJS it's a bit clearer that it fails by running out of memory.

**Comment by Tobias-Kohn** [comment]
The parser was stuck trying to make sense of the equal sign.  I added this case as another test case and the parser no responds with a "no viable alternative" error.
You might argue that it would be better to point out the missing right bracket.  If we look more closely, that error is recognised as well, but reported one position later than the equal sign.
